### ISSUE TITLE
Getting Unhandled Error

### ISSUE THREAD

**Issue by GitHubForMeat** [MattTW/HoneyAlarmServer#11]
Ok, not sure if this is appropriate to ask for help here.

I have an EVL-3 on a vista 20P and a IPDATATEL CBAT. 

Getting same result on WIN 8 (snip below) and a Raspberry Pi 

Help appreciated.

Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> ================================ RESTART ================================
>>> 
Using configuration file alarmserver.cfg
Config option pollinterval not set in [envisalink] defaulting to: '0'
Config option zonedumpinterval not set in [envisalink] defaulting to: '60'
Config option keypadupdateinterval not set in [envisalink] defaulting to: '60'
Config option commandtimeout not set in [envisalink] defaulting to: '30'
Config option kpeventtimeout not set in [envisalink] defaulting to: '45'
Wed, 21 Oct 2015 20:26:50 INFO <root alarmserver <module>> Alarm Server Starting
Wed, 21 Oct 2015 20:26:50 INFO <root alarmserver <module>> Currently Supporting Envisalink 2DS/3 only
Wed, 21 Oct 2015 20:26:50 INFO <root alarmserver <module>> Tested on a Honeywell Vista 15p + EVL-3
Wed, 21 Oct 2015 20:26:50 INFO <twisted _legacy publishToNewObserver> Starting factory <__main__.EnvisalinkClientFactory instance at 0x02F7D2D8>
Wed, 21 Oct 2015 20:26:50 DEBUG <root alarmserver startedConnecting> Started to connect to Envisalink...
Wed, 21 Oct 2015 20:26:50 INFO <twisted _legacy publishToNewObserver> Site starting on 8111
Wed, 21 Oct 2015 20:26:50 INFO <twisted _legacy publishToNewObserver> Starting factory <twisted.web.server.Site instance at 0x02FAB148>
Wed, 21 Oct 2015 20:26:51 DEBUG <root alarmserver buildProtocol> TCP connection estblished to 192.168.1.225:4025
Wed, 21 Oct 2015 20:26:51 DEBUG <root alarmserver buildProtocol> resetting connection delay
Wed, 21 Oct 2015 20:26:51 DEBUG <root basePlugin look_for_subclass> searching plugins.basePlugin
Wed, 21 Oct 2015 20:26:51 INFO <root alarmserver connectionMade> Connected to envisalink:4025
Wed, 21 Oct 2015 20:26:51 DEBUG <root alarmserver lineReceived> ----------------------------------------
Wed, 21 Oct 2015 20:26:51 DEBUG <root alarmserver lineReceived> RX < Login:
Wed, 21 Oct 2015 20:26:51 DEBUG <root alarmserver send_data> TX > user
Wed, 21 Oct 2015 20:26:51 DEBUG <root alarmserver lineReceived> ----------------------------------------
Wed, 21 Oct 2015 20:26:51 DEBUG <root alarmserver lineReceived> ----------------------------------------
Wed, 21 Oct 2015 20:26:51 DEBUG <root alarmserver lineReceived> RX < OK
Wed, 21 Oct 2015 20:26:51 INFO <root alarmserver handle_login_success> Password accepted, session created
Wed, 21 Oct 2015 20:26:51 DEBUG <root alarmserver lineReceived> ----------------------------------------
Wed, 21 Oct 2015 20:26:52 DEBUG <root alarmserver lineReceived> ----------------------------------------
Wed, 21 Oct 2015 20:26:52 DEBUG <root alarmserver lineReceived> RX < %00,01,0028,06,00,FAULT 06 KITCHENGARAGE DOOR     $
Wed, 21 Oct 2015 20:26:52 DEBUG <root alarmserver lineReceived> ----------------------------------------
Wed, 21 Oct 2015 20:26:55 DEBUG <root alarmserver lineReceived> ----------------------------------------
Wed, 21 Oct 2015 20:26:55 DEBUG <root alarmserver lineReceived> RX < %00,02,1C08,08,00,2   DISARMED      Ready to Arm  $
Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\python\log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\python\log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\python\context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\python\context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "C:\Python27\lib\site-packages\twisted\internet\tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "C:\Python27\lib\site-packages\twisted\internet\tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "C:\Python27\lib\site-packages\twisted\protocols\basic.py", line 454, in dataReceived
    self.lineReceived(line)
  File "C:\Users\Patrick\Documents\GitHub\HoneyAlarmServer\alarmserver.py", line 327, in lineReceived
    handlerFunc(data)
  File "C:\Users\Patrick\Documents\GitHub\HoneyAlarmServer\alarmserver.py", line 372, in handle_keypad_update
    ALARMSTATE['partition'][partitionNumber]['status'].update({'alarm': bool(flags.alarm), 'alarm_in_memory': bool(flags.alarm_in_memory), 'armed_away': bool(flags.armed_away),
exceptions.KeyError: 2

Wed, 21 Oct 2015 20:26:56 CRITICAL <twisted _legacy publishToNewObserver> Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\python\log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\python\log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\python\context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\python\context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "C:\Python27\lib\site-packages\twisted\internet\tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "C:\Python27\lib\site-packages\twisted\internet\tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "C:\Python27\lib\site-packages\twisted\protocols\basic.py", line 454, in dataReceived
    self.lineReceived(line)
  File "C:\Users\Patrick\Documents\GitHub\HoneyAlarmServer\alarmserver.py", line 327, in lineReceived
    handlerFunc(data)
  File "C:\Users\Patrick\Documents\GitHub\HoneyAlarmServer\alarmserver.py", line 372, in handle_keypad_update
    ALARMSTATE['partition'][partitionNumber]['status'].update({'alarm': bool(flags.alarm), 'alarm_in_memory': bool(flags.alarm_in_memory), 'armed_away': bool(flags.armed_away),
exceptions.KeyError: 2

Wed, 21 Oct 2015 20:26:56 INFO <root alarmserver connectionLost> Disconnected from envisalink:4025, reason was 2
Wed, 21 Oct 2015 20:26:56 DEBUG <root alarmserver logout> Ending Envisalink client connection...
Wed, 21 Oct 2015 20:26:56 DEBUG <root alarmserver clientConnectionLost> Lost connection to Envisalink.  Reason: [Failure instance: Traceback (failure with no frames): <type 'exceptions.KeyError'>: 2
]
Wed, 21 Oct 2015 20:26:56 INFO <twisted _legacy publishToNewObserver> <twisted.internet.tcp.Connector instance at 0x02F7D300> will retry in 2 seconds
Wed, 21 Oct 2015 20:26:56 INFO <twisted _legacy publishToNewObserver> Stopping factory <__main__.EnvisalinkClientFactory instance at 0x02F7D2D8>
Wed, 21 Oct 2015 20:26:58 INFO <twisted _legacy publishToNewObserver> Starting factory <__main__.EnvisalinkClientFactory instance at 0x02F7D2D8>
Wed, 21 Oct 2015 20:26:58 DEBUG <root alarmserver startedConnecting> Started to connect to Envisalink...
Wed, 21 Oct 2015 20:26:58 DEBUG <root alarmserver buildProtocol> TCP connection estblished to 192.168.1.225:4025
Wed, 21 Oct 2015 20:26:58 DEBUG <root alarmserver buildProtocol> resetting connection delay
Wed, 21 Oct 2015 20:26:58 DEBUG <root basePlugin look_for_subclass> searching plugins.basePlugin
Wed, 21 Oct 2015 20:26:58 INFO <root alarmserver connectionMade> Connected to envisalink:4025
Wed, 21 Oct 2015 20:26:58 DEBUG <root alarmserver lineReceived> ----------------------------------------
Wed, 21 Oct 2015 20:26:58 DEBUG <root alarmserver lineReceived> RX < Login:
Wed, 21 Oct 2015 20:26:58 DEBUG <root alarmserver send_data> TX > user
Wed, 21 Oct 2015 20:26:58 DEBUG <root alarmserver lineReceived> ----------------------------------------
Wed, 21 Oct 2015 20:26:58 DEBUG <root alarmserver lineReceived> ----------------------------------------
Wed, 21 Oct 2015 20:26:58 DEBUG <root alarmserver lineReceived> RX < OK
Wed, 21 Oct 2015 20:26:58 INFO <root alarmserver handle_login_success> Password accepted, session created
Wed, 21 Oct 2015 20:26:58 DEBUG <root alarmserver lineReceived> ----------------------------------------
Wed, 21 Oct 2015 20:27:00 DEBUG <root alarmserver lineReceived> ----------------------------------------
Wed, 21 Oct 2015 20:27:00 DEBUG <root alarmserver lineReceived> RX < %00,01,0028,06,00,FAULT 06 KITCHENGARAGE DOOR     $
Wed, 21 Oct 2015 20:27:00 DEBUG <root alarmserver lineReceived> ----------------------------------------
Wed, 21 Oct 2015 20:27:04 DEBUG <root alarmserver lineReceived> ----------------------------------------

**Comment by MattTW** [comment]
It looks like you have a second partition?  I haven't really tested this but the code should be able to handle it.   However, you must add the partition (partition2=Blah) to the config file so the AlarmState is initialized properly at startup - it isn't currently smart enough to dynamically add it.

**Comment by GitHubForMeat** [comment]
It was in there, but I didn't un-comment it out.

Works good now! Thanks.
