### ISSUE TITLE
Vista 128 panel

### ISSUE THREAD

**Issue by macjeff** [MattTW/HoneyAlarmServer#20]
Will it work with a Vista 128?

Jeff

**Comment by MattTW** [comment]
I know you asked this a couple months ago, sorry....

As long as it is supported by the Envisalink board it should work the interface that Envisalink returns is the same regardless of which supported Vista is used, however it has not been tested.   

Envisalink 4 supports:  Vista20P, 21iP, 15P, 10P, 128P, and 250P
