### ISSUE TITLE
Reporting to Smartthings

### ISSUE THREAD

**Issue by Sastozki** [MattTW/HoneyAlarmServer#5]
Hi @kholloway , 
I updated the code using the latest posted here. 

There appears to be an issue when a zone is triggered, its not reporting to Smartthings.  

Here is an example: 
Issue Overview:
1. Fault @ Zone20
2. The URL for the  Partition state is created and sent to SmartAPP. 
https://graph.api.smartthings.com/api/smartapps/installations/e204d268-af72-4e
23-89d4-9704491ec45d/panel/650/1?

Question: When or why would the zone URL get created? 

Note: I can change the zone with the test URL, which makes we believe the issue is here.

hu, 14 Aug 2014 14:52:35 DEBUG <root alarmserver lineReceived> RX < %00,01,0028,20,00,FAULT 20                        $
Thu, 14 Aug 2014 14:52:37 DEBUG <root alarmserver handle_partition_state_change> Parition 1 is in state READY
Thu, 14 Aug 2014 14:52:37 DEBUG <root alarmserver handle_partition_state_change> {"zone": {"2": {"status": {"fault": false, "alarm": false, "open": fa
lse, "tamper": false}, "lastevents": [], "name": "Front_Door", "lastfault": "Last Closed longer ago than I can remember"}, "3": {"status": {"fault": f
alse, "alarm": false, "open": false, "tamper": false}, "lastevents": [], "name": "LR_Windows", "lastfault": "Last Closed longer ago than I can remembe
r"}, "4": {"status": {"fault": false, "alarm": false, "open": false, "tamper": false}, "lastevents": [], "name": "DR_Windows", "lastfault": "Last Clos
ed longer ago than I can remember"}, "5": {"status": {"fault": false, "alarm": false, "open": false, "tamper": false}, "lastevents": [], "name": "Kitc
hen_Windows", "lastfault": "Last Closed longer ago than I can remember"}, "6": {"status": {"fault": false, "alarm": false, "open": false, "tamper": fa
lse}, "lastevents": [], "name": "BST_Windows", "lastfault": "Last Closed longer ago than I can remember"}, "17": {"status": {"fault": false, "alarm":
false, "open": false, "tamper": false}, "lastevents": [], "name": "Garage_Door", "lastfault": "Last Closed longer ago than I can remember"}, "lasteven
ts": [], "18": {"status": {"fault": false, "alarm": false, "open": false, "tamper": false}, "lastevents": [], "name": "Back_door", "lastfault": "Last
Closed longer ago than I can remember"}, "19": {"status": {"fault": false, "alarm": false, "open": false, "tamper": false}, "lastevents": [], "name":
"FR_Windows", "lastfault": "Last Closed longer ago than I can remember"}, "20": {"status": {"fault": false, "alarm": false, "open": false, "tamper": f
alse}, "lastevents": [], "name": "Foyer_Motion", "lastfault": "Last Closed longer ago than I can remember"}}, "partition": {"lastevents": [], "1": {"s
tatus": {"alarm_fire_zone": false, "fire": false, "entry_delay": false, "armed_stay": false, "armed_bypass": false, "ac_present": true, "alpha": "FAUL
T 20                        ", "ready": true, "chime": true, "trouble": false, "armed": false, "exit_delay": false, "alarm_in_memory": false, "beep":
"off", "alarm": false, "armed_away": false, "armed_zero_entry_delay": false}, "lastevents": [], "name": "Home", "lastfault": "Last Closed longer ago t
han I can remember"}}, "disarm": false, "version": 0.2, "cancel": false, "arm": true}
Thu, 14 Aug 2014 14:52:37 DEBUG <root smartthings partitionStatus> URL: https://graph.api.smartthings.com/api/smartapps/installations/e204d268-af72-4e
23-89d4-9704491ec45d/panel/650/1?

**Comment by MattTW** [comment]
Closing this issue, please open a new issue if there are still problems.
