### ISSUE TITLE
alarmserver.py - Line 573

### ISSUE THREAD

**Issue by Telecomgeek** [MattTW/HoneyAlarmServer#9]
There is a problem with alarmserver.py line 573

            return returnItems

This line is indented to far, which prevents the "for" loop from looping through all "inputItems".  Currently it will only return results for the first zone.  If the extra idents are removed to place it even with the "for" statement, it correctly loops through all the zones (i.e. inputItems).

**Comment by MattTW** [comment]
Thanks for reporting this!   I updated the source.
